""" Create a Turtle, name it, make it BLUE and draw a Smiley Face"""
import turtle
smile = turtle.Turtle()
smile.speed(0)
smile.color('blue')
smile.pu()
smile.left(90)
smile.forward(150)
smile.left(90)
smile.forward(100)
smile.pd()
smile.circle(5)
smile.pu()
smile.backward(200)
smile.pd()
smile.circle(5)
smile.pu()
smile.left(90)
smile.forward(150)
smile.right(90)
smile.backward(75)
smile.pd()
smile.left(90)
#smile.semicircle(1000)
for i in range(100):
    smile.forward(5)
    smile.right(1.8)
input()
